language: python

sudo: required

services:
- docker 

python:
- 2.7

install: true
- git clone https://github.com/neurolabusc/dcm_qa.git

before_script:
- docker build -t dcm2niix .

script: 
- docker run --rm=false -v $PWD:$PWD -w $PWD dcm2niix dcm_qa
