language: python

sudo: required

services:
- docker 

python:
- 2.7
- 3.5
- 3.5-dev

install:
- pip install boutiques
- git clone https://github.com/neurolabusc/dcm_qa.git

before_script:
- docker pull laletscaria/boutiques-dcm2niix:latest

script: 
- bosh exec launch dcm.json input.json
