language: python

sudo: required

services:
- docker 

python:
- 2.7
- 3.5
- 3.5-dev

install:
- git clone https://github.com/neurolabusc/dcm_qa.git

before_script:
- docker pull laletscaria/boutiques-dcm2niix:latest

script: 
- docker run --rm=false -v $PWD:$PWD -w $PWD laletscaria/boutiques-dcm2niix bosh exec launch dcm.json input.json
