language: python

sudo: required

services:
- docker 

python:
- 2.7
- 3.5
- 3.5-dev

install:
- git clone https://github.com/neurolabusc/dcm_qa.git

before_script:
- docker build -t dcm2niix_image -f Dockerfile .

script: 
- docker run --rm=false -v $PWD:$PWD -w $PWD dcm2niix_image mkdir -p Results;bosh exec launch dcm.json input.json
